import {
  LearningModuleDTO,
  LearningPracticeDTO,
  LearningImplementationDTO,
  CapstoneProjectDTO,
  CuratedResourceDTO,
  VerificationCheckpointDTO,
} from "./types";

export interface SkillCurriculumDefinition {
  skillId: string;
  canonicalSkill: string;
  version: number;
  description: string;
  targetRoles: string[];
  prerequisites: string[];
  estimatedHours: number;
  whyItMatters: string;
  modules: {
    id: string;
    title: string;
    description: string;
    level: "beginner" | "intermediate" | "advanced";
    order: number;
    estimatedHours: number;
    topics: {
      id: string;
      title: string;
      description: string;
      order: number;
      required: boolean;
      estimatedMinutes: number;
      prerequisites: string[];
      primaryResource: Omit<CuratedResourceDTO, "skillId" | "topicId">;
      alternativeResource?: Omit<CuratedResourceDTO, "skillId" | "topicId">;
      practiceTasks?: Omit<LearningPracticeDTO, "topicId">[];
      checkpoint?: Omit<VerificationCheckpointDTO, "topicId">;
    }[];
  }[];
  implementationTasks: Omit<LearningImplementationDTO, "skillId">[];
  capstoneProject: CapstoneProjectDTO;
}

export const SEEDED_CURRICULA: Record<string, SkillCurriculumDefinition> = {
  // ==========================================
  // 1. POSTGRESQL
  // ==========================================
  PostgreSQL: {
    skillId: "PostgreSQL",
    canonicalSkill: "PostgreSQL",
    version: 1,
    description: "Enterprise-grade relational database management system emphasizing ACID compliance, high concurrency, and advanced indexing.",
    targetRoles: ["Backend Engineer", "Full Stack Developer", "Data Engineer", "Database Administrator"],
    prerequisites: ["Basic Terminal / CLI", "Basic Data Modeling Concepts"],
    estimatedHours: 24,
    whyItMatters: "PostgreSQL is the world's most advanced open-source database. Top tier tech companies and fintech scale on its MVCC engine, advanced indexing, JSONB support, and bulletproof transactional integrity.",
    modules: [
      {
        id: "pg-mod-1",
        title: "Relational Modeling & PostgreSQL Fundamentals",
        description: "Foundations of relational database design, data types, constraints, and relational normalization in PostgreSQL.",
        level: "beginner",
        order: 1,
        estimatedHours: 5,
        topics: [
          {
            id: "pg-top-schema",
            title: "Relational Schemas & Constraints",
            description: "Design relational schemas with PRIMARY KEY, FOREIGN KEY, CHECK, NOT NULL, and cascading deletes.",
            order: 1,
            required: true,
            estimatedMinutes: 60,
            prerequisites: [],
            primaryResource: {
              id: "res-pg-schema-official",
              title: "PostgreSQL Official Documentation: Data Definition & Constraints",
              url: "https://www.postgresql.org/docs/current/ddl-constraints.html",
              provider: "PostgreSQL Global Development Group",
              resourceType: "official_docs",
              level: "beginner",
              isFree: true,
              isOfficial: true,
              qualityScore: 98,
              interactive: false,
              projectBased: false,
              estimatedMinutes: 45,
              status: "active",
              isPrimary: true,
              whyThisResource: "The canonical guide to defining tables, foreign keys, and integrity constraints.",
            },
            alternativeResource: {
              id: "res-pg-schema-fcc",
              title: "freeCodeCamp: Relational Database Course & Schema Design",
              url: "https://www.freecodecamp.org/news/relational-database-course-freecodecamp/",
              provider: "freeCodeCamp",
              resourceType: "structured_course",
              level: "beginner",
              isFree: true,
              isOfficial: false,
              qualityScore: 90,
              interactive: true,
              projectBased: true,
              estimatedMinutes: 60,
              status: "active",
              isPrimary: false,
              whyThisResource: "Hands-on guided tutorials building relational schemas in PostgreSQL.",
            },
            practiceTasks: [
              {
                id: "pg-prac-schema-1",
                title: "Design an E-Commerce Schema with Foreign Keys",
                description: "Write DDL for `users`, `orders`, `order_items`, and `products` with ON DELETE CASCADE constraints and sensible default timestamps.",
                difficulty: "beginner",
                expectedOutcome: "DDL script successfully executes without syntax or constraint errors.",
                verificationMethod: "manual_check",
                order: 1,
                hints: ["Remember to place FOREIGN KEY constraints on child tables referencing parent primary keys."],
              },
            ],
            checkpoint: {
              id: "pg-chk-schema",
              title: "Relational Constraints Mastery Check",
              description: "Validate your understanding of foreign key cascade behaviors and unique constraints.",
              checkpointType: "quiz",
              questions: [
                {
                  id: "pg-q1",
                  question: "What happens to child records when a parent record is deleted if the foreign key specifies ON DELETE CASCADE?",
                  options: [
                    "Child records are automatically deleted as well",
                    "The deletion of the parent fails with a foreign key violation",
                    "Child foreign keys are set to NULL",
                    "Child records remain orphaned in the table",
                  ],
                  correctIndex: 0,
                  explanation: "ON DELETE CASCADE propagates the deletion of the referenced row to all referencing rows.",
                },
              ],
              verificationCriteria: ["Understand ON DELETE CASCADE vs RESTRICT vs SET NULL."],
            },
          },
          {
            id: "pg-top-joins",
            title: "Advanced Queries, JOINs & Aggregations",
            description: "Master INNER, LEFT, RIGHT, and FULL OUTER joins, GROUP BY, HAVING, and window aggregations.",
            order: 2,
            required: true,
            estimatedMinutes: 75,
            prerequisites: ["pg-top-schema"],
            primaryResource: {
              id: "res-pg-joins-official",
              title: "PostgreSQL Official Documentation: Queries & Table Expressions",
              url: "https://www.postgresql.org/docs/current/queries-table-expressions.html",
              provider: "PostgreSQL Global Development Group",
              resourceType: "official_docs",
              level: "beginner",
              isFree: true,
              isOfficial: true,
              qualityScore: 97,
              interactive: false,
              projectBased: false,
              estimatedMinutes: 50,
              status: "active",
              isPrimary: true,
              whyThisResource: "Complete authoritative breakdown of JOIN mechanics and CTE table expressions.",
            },
            alternativeResource: {
              id: "res-pg-sqlzoo",
              title: "SQLZoo Interactive Relational JOIN Tutorial",
              url: "https://sqlzoo.net/wiki/The_JOIN_operation",
              provider: "SQLZoo",
              resourceType: "interactive",
              level: "beginner",
              isFree: true,
              isOfficial: false,
              qualityScore: 92,
              interactive: true,
              projectBased: false,
              estimatedMinutes: 45,
              status: "active",
              isPrimary: false,
              whyThisResource: "Live interactive SQL editor with immediate feedback on query results.",
            },
            practiceTasks: [
              {
                id: "pg-prac-joins-1",
                title: "Calculate Customer Lifetime Value (LTV) with LEFT JOIN",
                description: "Write an aggregate query joining users with orders to sum total expenditure per user, including users with 0 orders using COALESCE.",
                difficulty: "beginner",
                expectedOutcome: "Result set includes all users, with 0 for inactive users and total spent for active purchasers.",
                verificationMethod: "code_execution",
                order: 1,
              },
            ],
          },
        ],
      },
      {
        id: "pg-mod-2",
        title: "Indexing, Execution Plans & Performance Optimization",
        description: "B-Tree indexes, GIN indexes, EXPLAIN ANALYZE execution plan breakdown, and query tuning.",
        level: "intermediate",
        order: 2,
        estimatedHours: 8,
        topics: [
          {
            id: "pg-top-indexes",
            title: "PostgreSQL Indexes: B-Tree, Composite & GIN",
            description: "Understand index data structures, index selectivity, composite index column order, and JSONB indexing with GIN.",
            order: 1,
            required: true,
            estimatedMinutes: 90,
            prerequisites: ["pg-top-joins"],
            primaryResource: {
              id: "res-pg-indexes-official",
              title: "PostgreSQL Official Documentation: Index Types & B-Tree Mechanics",
              url: "https://www.postgresql.org/docs/current/indexes-types.html",
              provider: "PostgreSQL Global Development Group",
              resourceType: "official_docs",
              level: "intermediate",
              isFree: true,
              isOfficial: true,
              qualityScore: 99,
              interactive: false,
              projectBased: false,
              estimatedMinutes: 60,
              status: "active",
              isPrimary: true,
              whyThisResource: "Detailed explanation of B-tree, Hash, GiST, SP-GiST, GIN, and BRIN indexes.",
            },
            alternativeResource: {
              id: "res-pg-use-the-index",
              title: "Use The Index, Luke! - Complete Guide to Database Indexing",
              url: "https://use-the-index-luke.com/sql/indexing-anatomy",
              provider: "Markus Winand",
              resourceType: "tutorial",
              level: "intermediate",
              isFree: true,
              isOfficial: false,
              qualityScore: 95,
              interactive: false,
              projectBased: true,
              estimatedMinutes: 70,
              status: "active",
              isPrimary: false,
              whyThisResource: "World-renowned visual explanation of B-tree search traversal and composite index column ordering.",
            },
            practiceTasks: [
              {
                id: "pg-prac-idx-1",
                title: "Construct an Optimal Multi-Column Composite Index",
                description: "Given a query filtering `status = 'ACTIVE'` and sorting by `created_at DESC`, decide the optimal column ordering for a B-Tree index.",
                difficulty: "intermediate",
                expectedOutcome: "Index created as `(status, created_at DESC)` avoiding in-memory filesort.",
                verificationMethod: "manual_check",
                order: 1,
              },
            ],
            checkpoint: {
              id: "pg-chk-index",
              title: "Indexing & Selectivity Checkpoint",
              description: "Test your knowledge of index applicability and composite index prefix rules.",
              checkpointType: "quiz",
              questions: [
                {
                  id: "pg-idx-q1",
                  question: "If a composite index is created on (country, city, postal_code), which of the following WHERE clauses CANNOT use this index?",
                  options: [
                    "WHERE city = 'Berlin'",
                    "WHERE country = 'Germany' AND city = 'Berlin'",
                    "WHERE country = 'Germany'",
                    "WHERE country = 'Germany' AND city = 'Berlin' AND postal_code = '10115'",
                  ],
                  correctIndex: 0,
                  explanation: "B-Tree composite indexes can only be utilized from the leftmost prefix. Filtering on 'city' alone skips the leading 'country' column.",
                },
              ],
              verificationCriteria: ["Explain leftmost prefix rule of composite B-tree indexes."],
            },
          },
          {
            id: "pg-top-explain",
            title: "EXPLAIN (ANALYZE, BUFFERS) & Query Planner",
            description: "Read PostgreSQL execution plans, spot sequential table scans, buffer cache hits vs disk reads, and nested loop vs hash joins.",
            order: 2,
            required: true,
            estimatedMinutes: 90,
            prerequisites: ["pg-top-indexes"],
            primaryResource: {
              id: "res-pg-explain-official",
              title: "PostgreSQL Official Documentation: Using EXPLAIN & Query Performance",
              url: "https://www.postgresql.org/docs/current/using-explain.html",
              provider: "PostgreSQL Global Development Group",
              resourceType: "official_docs",
              level: "intermediate",
              isFree: true,
              isOfficial: true,
              qualityScore: 98,
              interactive: false,
              projectBased: false,
              estimatedMinutes: 60,
              status: "active",
              isPrimary: true,
              whyThisResource: "The official manual explaining cost estimation, actual time, loops, and buffer stats.",
            },
            alternativeResource: {
              id: "res-pg-explain-dalibo",
              title: "Dalibo Explain PostgreSQL Visualizer & Guide",
              url: "https://explain.dalibo.com/",
              provider: "Dalibo",
              resourceType: "interactive",
              level: "intermediate",
              isFree: true,
              isOfficial: false,
              qualityScore: 92,
              interactive: true,
              projectBased: false,
              estimatedMinutes: 40,
              status: "active",
              isPrimary: false,
              whyThisResource: "Paste your raw EXPLAIN (ANALYZE, BUFFERS, FORMAT JSON) output to visually identify bottlenecks.",
            },
            practiceTasks: [
              {
                id: "pg-prac-explain-1",
                title: "Diagnose and Eliminate a Sequential Scan on 100K Rows",
                description: "Generate 100,000 synthetic rows with `generate_series`. Run EXPLAIN ANALYZE, observe Seq Scan cost, add a partial index, and verify Index Scan.",
                difficulty: "intermediate",
                expectedOutcome: "Execution time drops by >90% and plan shows Index Scan instead of Seq Scan.",
                verificationMethod: "explain_analyze",
                order: 1,
              },
            ],
          },
        ],
      },
      {
        id: "pg-mod-3",
        title: "Transactions, Concurrency, Locking & MVCC",
        description: "ACID guarantees, transaction isolation levels, row locks (SELECT FOR UPDATE), deadlocks, and multi-version concurrency control.",
        level: "advanced",
        order: 3,
        estimatedHours: 6,
        topics: [
          {
            id: "pg-top-acid-locks",
            title: "Transactions, Row Locks & Deadlock Prevention",
            description: "Atomic operations with BEGIN/COMMIT/ROLLBACK, row-level locks with SELECT FOR UPDATE, and deadlock resolution.",
            order: 1,
            required: true,
            estimatedMinutes: 80,
            prerequisites: ["pg-top-joins"],
            primaryResource: {
              id: "res-pg-locks-official",
              title: "PostgreSQL Official Documentation: Explicit Locking & Row-Level Locks",
              url: "https://www.postgresql.org/docs/current/explicit-locking.html",
              provider: "PostgreSQL Global Development Group",
              resourceType: "official_docs",
              level: "advanced",
              isFree: true,
              isOfficial: true,
              qualityScore: 97,
              interactive: false,
              projectBased: false,
              estimatedMinutes: 50,
              status: "active",
              isPrimary: true,
              whyThisResource: "Essential reading for preventing race conditions in financial ledger and inventory systems.",
            },
            practiceTasks: [
              {
                id: "pg-prac-lock-1",
                title: "Prevent Double-Spending with SELECT FOR UPDATE",
                description: "Write a transactional balance transfer script between two accounts that locks rows in consistent primary key order to prevent deadlocks.",
                difficulty: "advanced",
                expectedOutcome: "Concurrent transfers succeed without overdrafts or deadlock exceptions.",
                verificationMethod: "code_execution",
                order: 1,
              },
            ],
          },
          {
            id: "pg-top-mvcc",
            title: "Isolation Levels & MVCC (Multi-Version Concurrency Control)",
            description: "Read Committed, Repeatable Read, and Serializable. Understand how Postgres handles dirty reads, non-repeatable reads, and serialization anomalies.",
            order: 2,
            required: true,
            estimatedMinutes: 90,
            prerequisites: ["pg-top-acid-locks"],
            primaryResource: {
              id: "res-pg-mvcc-official",
              title: "PostgreSQL Official Documentation: Transaction Isolation & MVCC",
              url: "https://www.postgresql.org/docs/current/transaction-iso.html",
              provider: "PostgreSQL Global Development Group",
              resourceType: "official_docs",
              level: "advanced",
              isFree: true,
              isOfficial: true,
              qualityScore: 98,
              interactive: false,
              projectBased: false,
              estimatedMinutes: 60,
              status: "active",
              isPrimary: true,
              whyThisResource: "In-depth breakdown of transaction snapshotting, vacuuming dead tuples, and isolation guarantees.",
            },
            checkpoint: {
              id: "pg-chk-mvcc",
              title: "Concurrency & Isolation Verification",
              description: "Validate comprehension of phantom reads and serializable snapshot isolation.",
              checkpointType: "quiz",
              questions: [
                {
                  id: "pg-mvcc-q1",
                  question: "What is PostgreSQL's default transaction isolation level?",
                  options: [
                    "Read Committed",
                    "Repeatable Read",
                    "Read Uncommitted",
                    "Serializable",
                  ],
                  correctIndex: 0,
                  explanation: "PostgreSQL defaults to Read Committed, where each query within a transaction sees only data committed before that query began.",
                },
              ],
              verificationCriteria: ["Distinguish Read Committed from Repeatable Read and Serializable."],
            },
          },
        ],
      },
      {
        id: "pg-mod-4",
        title: "Partitioning, Connection Pooling & Production Reliability",
        description: "Declarative table partitioning, connection pooling with pgBouncer, WAL replication, and maintenance.",
        level: "advanced",
        order: 4,
        estimatedHours: 5,
        topics: [
          {
            id: "pg-top-partitioning",
            title: "Declarative Table Partitioning",
            description: "Implement range and list partitioning on high-volume time-series or multi-tenant datasets for query pruning.",
            order: 1,
            required: false,
            estimatedMinutes: 75,
            prerequisites: ["pg-top-indexes"],
            primaryResource: {
              id: "res-pg-partitioning-official",
              title: "PostgreSQL Official Documentation: Table Partitioning",
              url: "https://www.postgresql.org/docs/current/ddl-partitioning.html",
              provider: "PostgreSQL Global Development Group",
              resourceType: "official_docs",
              level: "advanced",
              isFree: true,
              isOfficial: true,
              qualityScore: 96,
              interactive: false,
              projectBased: false,
              estimatedMinutes: 50,
              status: "active",
              isPrimary: true,
              whyThisResource: "Covers declarative range, list, and hash partitioning with partition pruning.",
            },
            practiceTasks: [
              {
                id: "pg-prac-part-1",
                title: "Create a Monthly Partitioned Audit Log Table",
                description: "Partition an audit log table by `created_at` timestamp across 12 months with automatic partition routing.",
                difficulty: "advanced",
                expectedOutcome: "Inserts route automatically to monthly child tables; queries with date bounds prune irrelevant partitions.",
                verificationMethod: "manual_check",
                order: 1,
              },
            ],
          },
        ],
      },
    ],
    implementationTasks: [
      {
        id: "pg-impl-order-api",
        title: "Build a Scalable Order Processing API with PostgreSQL",
        description: "Develop a high-throughput order management REST API with normalized schema, connection pooling, and ACID guarantees.",
        requirements: [
          "Create normalized tables: users, products, orders, order_items with foreign keys and cascade rules.",
          "Implement transactional checkout endpoint using BEGIN/COMMIT and SELECT FOR UPDATE on product inventory.",
          "Add composite B-Tree index on orders(user_id, status, created_at DESC).",
          "Implement paginated query endpoint using cursor-based pagination (keyset pagination) instead of OFFSET.",
          "Benchmark with 100,000 synthetic rows and capture EXPLAIN (ANALYZE, BUFFERS) proof.",
        ],
        expectedTechnologies: ["PostgreSQL", "Node.js/Express or Python/FastAPI", "SQL / Prisma ORM"],
        difficulty: "intermediate",
        estimatedHours: 10,
        order: 1,
        isCapstone: false,
      },
    ],
    capstoneProject: {
      id: "pg-capstone-main",
      title: "High-Volume Financial Ledger & Analytics Service",
      description: "Build a production-grade double-entry financial ledger and transaction processing system with strict ACID guarantees, query-optimized analytical reporting, and audit trail partitioning.",
      architectureOverview: "The system models accounts, entries, and journal transactions using double-entry bookkeeping rules where debits equal credits. High concurrency is handled via pessimistic locking, and read heavy dashboards leverage indexed materializations and partitioned log tables.",
      requirements: [
        "Double-entry bookkeeping schema enforcing sum(debits) = sum(credits) per transaction.",
        "Row-level locking on account balance rows during fund transfer to prevent double-spending.",
        "Declarative monthly partitioning on the transaction_audit_log table.",
        "Cursor-based paginated ledger statement API with sub-15ms response times on 500k records.",
        "Comprehensive EXPLAIN ANALYZE benchmark demonstrating zero sequential table scans on core queries.",
        "Dockerized PostgreSQL setup with healthcheck and automated migration scripts.",
      ],
      expectedTechnologies: ["PostgreSQL 15+", "Node.js / Go / Python", "Docker", "pgBouncer / Connection Pooler"],
      estimatedHours: 14,
      portfolioDeliverables: {
        githubRepoRequired: true,
        readmeSpec: "Include ER diagram, architectural overview, DDL migration files, and EXPLAIN ANALYZE latency benchmarks.",
        liveDemoSuggested: true,
      },
    },
  },

  // ==========================================
  // 2. DOCKER
  // ==========================================
  Docker: {
    skillId: "Docker",
    canonicalSkill: "Docker",
    version: 1,
    description: "Standard containerization platform for creating, deploying, and running applications in lightweight, isolated environments.",
    targetRoles: ["DevOps Engineer", "Backend Developer", "Cloud Architect", "Platform Engineer"],
    prerequisites: ["Linux Command Line", "Basic Networking (Ports, IP)"],
    estimatedHours: 20,
    whyItMatters: "Docker standardizes software execution across development, CI/CD, and multi-cloud Kubernetes clusters. It eliminates 'works on my machine' defects and is required across backend and infrastructure roles.",
    modules: [
      {
        id: "dk-mod-1",
        title: "Containers, Primitives & Core CLI",
        description: "Container primitives (namespaces, cgroups), images vs containers, and container lifecycle operations.",
        level: "beginner",
        order: 1,
        estimatedHours: 4,
        topics: [
          {
            id: "dk-top-lifecycle",
            title: "Container Lifecycle & Core CLI Commands",
            description: "Run, inspect, stop, attach, view logs, and clean up containers with docker run, ps, exec, logs, and prune.",
            order: 1,
            required: true,
            estimatedMinutes: 60,
            prerequisites: [],
            primaryResource: {
              id: "res-dk-getstarted-official",
              title: "Docker Official Documentation: Getting Started & Container Concepts",
              url: "https://docs.docker.com/get-started/",
              provider: "Docker, Inc.",
              resourceType: "official_docs",
              level: "beginner",
              isFree: true,
              isOfficial: true,
              qualityScore: 98,
              interactive: false,
              projectBased: false,
              estimatedMinutes: 45,
              status: "active",
              isPrimary: true,
              whyThisResource: "The canonical starting point explaining containers, images, and container isolation.",
            },
            alternativeResource: {
              id: "res-dk-pwd",
              title: "Play with Docker (Free Interactive In-Browser Terminal)",
              url: "https://labs.play-with-docker.com/",
              provider: "Docker Community",
              resourceType: "interactive",
              level: "beginner",
              isFree: true,
              isOfficial: true,
              qualityScore: 92,
              interactive: true,
              projectBased: false,
              estimatedMinutes: 45,
              status: "active",
              isPrimary: false,
              whyThisResource: "Free browser-based Docker sandbox allowing you to run containers without local installation.",
            },
            practiceTasks: [
              {
                id: "dk-prac-cli-1",
                title: "Run an Nginx Container with Port Forwarding & Environment Vars",
                description: "Run an official Nginx container in detached mode mapped to host port 8080, inspect container IP, and tail its access logs.",
                difficulty: "beginner",
                expectedOutcome: "HTTP request to localhost:8080 returns Nginx welcome page and log shows GET / entry.",
                verificationMethod: "code_execution",
                order: 1,
              },
            ],
            checkpoint: {
              id: "dk-chk-lifecycle",
              title: "Docker CLI & Primitives Checkpoint",
              description: "Test your knowledge of container persistence and port binding.",
              checkpointType: "quiz",
              questions: [
                {
                  id: "dk-q1",
                  question: "In `docker run -p 3000:8080 my-app`, which port is the host port and which is the container port?",
                  options: [
                    "Host port is 3000, container port is 8080",
                    "Host port is 8080, container port is 3000",
                    "Both ports are exposed on the host",
                    "Port 3000 is internal only",
                  ],
                  correctIndex: 0,
                  explanation: "The syntax is `-p <HOST_PORT>:<CONTAINER_PORT>`.",
                },
              ],
              verificationCriteria: ["Correctly interpret host vs container port mappings."],
            },
          },
          {
            id: "dk-top-dockerfile",
            title: "Writing Optimized Dockerfiles & Layer Caching",
            description: "Master FROM, COPY, RUN, CMD, ENTRYPOINT, and how Docker caches intermediate image layers.",
            order: 2,
            required: true,
            estimatedMinutes: 75,
            prerequisites: ["dk-top-lifecycle"],
            primaryResource: {
              id: "res-dk-best-practices",
              title: "Docker Official Documentation: Dockerfile Best Practices Guide",
              url: "https://docs.docker.com/develop/develop-images/dockerfile_best-practices/",
              provider: "Docker, Inc.",
              resourceType: "official_docs",
              level: "beginner",
              isFree: true,
              isOfficial: true,
              qualityScore: 99,
              interactive: false,
              projectBased: false,
              estimatedMinutes: 50,
              status: "active",
              isPrimary: true,
              whyThisResource: "Essential guide covering caching order, .dockerignore, and minimizing layer count.",
            },
            practiceTasks: [
              {
                id: "dk-prac-cache-1",
                title: "Optimize Dependency Layer Caching in a Node/Python Dockerfile",
                description: "Structure a Dockerfile so `package.json` / `requirements.txt` is copied and installed BEFORE copying application source code.",
                difficulty: "beginner",
                expectedOutcome: "Changing source code does not trigger re-installation of dependencies during subsequent builds.",
                verificationMethod: "manual_check",
                order: 1,
              },
            ],
          },
        ],
      },
      {
        id: "dk-mod-2",
        title: "Multi-Stage Builds, Volumes & Networking",
        description: "Shrink image footprints by up to 90%, configure named volumes for stateful databases, and isolate bridge networks.",
        level: "intermediate",
        order: 2,
        estimatedHours: 6,
        topics: [
          {
            id: "dk-top-multistage",
            title: "Multi-Stage Builds & Distroless/Alpine Images",
            description: "Compile code in temporary build stages and copy only production artifacts into minimal runtime bases.",
            order: 1,
            required: true,
            estimatedMinutes: 80,
            prerequisites: ["dk-top-dockerfile"],
            primaryResource: {
              id: "res-dk-multistage-official",
              title: "Docker Official Documentation: Multi-Stage Builds",
              url: "https://docs.docker.com/build/building/multi-stage/",
              provider: "Docker, Inc.",
              resourceType: "official_docs",
              level: "intermediate",
              isFree: true,
              isOfficial: true,
              qualityScore: 98,
              interactive: false,
              projectBased: false,
              estimatedMinutes: 50,
              status: "active",
              isPrimary: true,
              whyThisResource: "Official instructions for creating tiny, secure, hardened production containers.",
            },
            practiceTasks: [
              {
                id: "dk-prac-multi-1",
                title: "Reduce an Image from 1GB to Under 100MB with Multi-Stage",
                description: "Build a TypeScript or Go application with a builder stage and copy compiled output to an `alpine` or `distroless` final image.",
                difficulty: "intermediate",
                expectedOutcome: "Final image size is verified under 100MB using `docker images`.",
                verificationMethod: "manual_check",
                order: 1,
              },
            ],
          },
          {
            id: "dk-top-networking-volumes",
            title: "Docker Networking & Persistent Storage Volumes",
            description: "Bridge networks, DNS discovery between containers, named volumes, and bind mounts for local developer syncing.",
            order: 2,
            required: true,
            estimatedMinutes: 75,
            prerequisites: ["dk-top-multistage"],
            primaryResource: {
              id: "res-dk-storage-official",
              title: "Docker Official Documentation: Manage Data & Volumes",
              url: "https://docs.docker.com/storage/volumes/",
              provider: "Docker, Inc.",
              resourceType: "official_docs",
              level: "intermediate",
              isFree: true,
              isOfficial: true,
              qualityScore: 96,
              interactive: false,
              projectBased: false,
              estimatedMinutes: 45,
              status: "active",
              isPrimary: true,
              whyThisResource: "Explains named volumes, host bind mounts, and database data survival after container removal.",
            },
            practiceTasks: [
              {
                id: "dk-prac-vol-1",
                title: "Persist Database Data Across Container Restarts",
                description: "Attach a named volume `pgdata` to a Postgres container, insert rows, delete container, start a new container, and verify data survives.",
                difficulty: "intermediate",
                expectedOutcome: "Inserted records remain queryable in the second container instance.",
                verificationMethod: "code_execution",
                order: 1,
              },
            ],
          },
        ],
      },
      {
        id: "dk-mod-3",
        title: "Docker Compose & Multi-Container Topologies",
        description: "Orchestrate multi-service topologies (Web API, Cache, Relational DB) with healthchecks, secrets, and environment variables.",
        level: "intermediate",
        order: 3,
        estimatedHours: 5,
        topics: [
          {
            id: "dk-top-compose",
            title: "Multi-Service Orchestration with Docker Compose",
            description: "Define services, networks, depends_on conditions with healthchecks, and environment files in compose.yaml.",
            order: 1,
            required: true,
            estimatedMinutes: 90,
            prerequisites: ["dk-top-networking-volumes"],
            primaryResource: {
              id: "res-dk-compose-official",
              title: "Docker Official Documentation: Docker Compose Specification & Guide",
              url: "https://docs.docker.com/compose/",
              provider: "Docker, Inc.",
              resourceType: "official_docs",
              level: "intermediate",
              isFree: true,
              isOfficial: true,
              qualityScore: 99,
              interactive: false,
              projectBased: false,
              estimatedMinutes: 50,
              status: "active",
              isPrimary: true,
              whyThisResource: "Canonical reference for multi-container orchestration with dependencies and environment configuration.",
            },
            practiceTasks: [
              {
                id: "dk-prac-compose-1",
                title: "Spin Up a Full-Stack Topology with Healthcheck Dependencies",
                description: "Write `compose.yaml` with a Node.js API, PostgreSQL, and Redis, configuring API `depends_on` with `condition: service_healthy`.",
                difficulty: "intermediate",
                expectedOutcome: "Executing `docker compose up` starts DB and Redis, waits for healthcheck, then starts API without connection crashes.",
                verificationMethod: "manual_check",
                order: 1,
              },
            ],
          },
        ],
      },
      {
        id: "dk-mod-4",
        title: "Container Security, Hardening & CI/CD",
        description: "Non-root user execution, dropping Linux capabilities, vulnerability scanning, and automated GitHub Actions build pipelines.",
        level: "advanced",
        order: 4,
        estimatedHours: 5,
        topics: [
          {
            id: "dk-top-security",
            title: "Container Hardening, Non-Root Users & Trivy Scanning",
            description: "Switch to dedicated non-root users (`USER node` or `USER app`), make file systems read-only, and scan CVEs with Docker Scout / Trivy.",
            order: 1,
            required: true,
            estimatedMinutes: 80,
            prerequisites: ["dk-top-compose"],
            primaryResource: {
              id: "res-dk-security-official",
              title: "Docker Official Documentation: Docker Security Best Practices",
              url: "https://docs.docker.com/engine/security/",
              provider: "Docker, Inc.",
              resourceType: "official_docs",
              level: "advanced",
              isFree: true,
              isOfficial: true,
              qualityScore: 97,
              interactive: false,
              projectBased: false,
              estimatedMinutes: 50,
              status: "active",
              isPrimary: true,
              whyThisResource: "Detailed instructions on container boundary isolation, rootless Docker, and kernel attack surface reduction.",
            },
            checkpoint: {
              id: "dk-chk-sec",
              title: "Container Security Checkpoint",
              description: "Verify knowledge of container privilege separation.",
              checkpointType: "quiz",
              questions: [
                {
                  id: "dk-sec-q1",
                  question: "Why should production containers avoid running as the default root (UID 0) user?",
                  options: [
                    "If a container breakout vulnerability occurs, the attacker gains host root privileges",
                    "Root users consume double the memory of non-root users",
                    "Docker daemon fails to start containers running as root",
                    "Alpine base images do not contain a root user",
                  ],
                  correctIndex: 0,
                  explanation: "Container processes running as root share the host kernel; an escape exploit grants root execution on the host machine.",
                },
              ],
              verificationCriteria: ["Explain privilege escalation risks in containerized environments."],
            },
          },
        ],
      },
    ],
    implementationTasks: [
      {
        id: "dk-impl-compose-stack",
        title: "Containerize a Full-Stack Production Environment",
        description: "Containerize a multi-tier web application (Next.js frontend, REST API backend, PostgreSQL database, and Redis cache) with production-ready multi-stage Dockerfiles.",
        requirements: [
          "Create multi-stage Dockerfiles for frontend and backend keeping final images under 150MB.",
          "Enforce non-root execution inside all application containers.",
          "Orchestrate via docker-compose.yml with private internal bridge networks and persistent named volumes.",
          "Configure healthchecks for PostgreSQL and Redis to sequence service startup cleanly.",
          "Set up a GitHub Actions workflow that builds, tests, and scans images for vulnerabilities.",
        ],
        expectedTechnologies: ["Docker", "Docker Compose", "Multi-stage builds", "GitHub Actions", "Trivy / Scout"],
        difficulty: "intermediate",
        estimatedHours: 8,
        order: 1,
        isCapstone: false,
      },
    ],
    capstoneProject: {
      id: "dk-capstone-main",
      title: "Production Containerized Microservices Topology & CI/CD Pipeline",
      description: "Architect and containerize an enterprise-style multi-service application with automated multi-platform image builds, security scanning, health-checked orchestration, and zero-downtime deployment scripts.",
      architectureOverview: "Consists of an API Gateway (Reverse Proxy), an Authentication Service, a Core Business API, PostgreSQL database with persistent volume backups, and a Redis message queue, completely decoupled across isolated Docker bridge networks.",
      requirements: [
        "Multi-stage Dockerfiles for each microservice with minimal base images (Alpine or Distroless).",
        "Security audit passing Trivy scan with 0 CRITICAL or HIGH unpatched vulnerabilities.",
        "Docker Compose orchestration with separate frontend and backend bridge networks.",
        "Graceful container shutdown handling SIGTERM signals in application code.",
        "Automated CI/CD pipeline building multi-arch images (linux/amd64, linux/arm64) and tagging with Git SHAs.",
        "Documentation detailing local development setup, backup procedures, and production deployment instructions.",
      ],
      expectedTechnologies: ["Docker", "Docker Compose", "Nginx / Caddy", "GitHub Actions", "Linux / Bash"],
      estimatedHours: 12,
      portfolioDeliverables: {
        githubRepoRequired: true,
        readmeSpec: "Detailed README with architecture diagram, step-by-step setup, Dockerfile rationale, and security scan reports.",
        liveDemoSuggested: false,
      },
    },
  },

  // ==========================================
  // 3. AWS (AMAZON WEB SERVICES)
  // ==========================================
  AWS: {
    skillId: "AWS",
    canonicalSkill: "AWS",
    version: 1,
    description: "The world's leading cloud computing platform offering compute, storage, networking, managed databases, and cloud security services.",
    targetRoles: ["Cloud Engineer", "Backend Developer", "DevOps Engineer", "Solutions Architect"],
    prerequisites: ["Networking Basics (IP, CIDR, DNS, HTTP)", "Linux CLI"],
    estimatedHours: 25,
    whyItMatters: "Over 60% of cloud-native companies run their core infrastructure on AWS. Demonstrating practical mastery of IAM, VPC, EC2, S3, RDS, and CloudWatch is essential for modern software engineering positions.",
    modules: [
      {
        id: "aws-mod-1",
        title: "Cloud Fundamentals, IAM & Security Architecture",
        description: "AWS shared responsibility model, IAM users, groups, roles, policies, and least-privilege security.",
        level: "beginner",
        order: 1,
        estimatedHours: 5,
        topics: [
          {
            id: "aws-top-iam",
            title: "AWS Identity and Access Management (IAM) & Least Privilege",
            description: "Understand IAM policies (Effect, Action, Resource), IAM roles for EC2/Lambda, and multi-factor authentication (MFA).",
            order: 1,
            required: true,
            estimatedMinutes: 75,
            prerequisites: [],
            primaryResource: {
              id: "res-aws-iam-official",
              title: "AWS Official Documentation: IAM User Guide & Best Practices",
              url: "https://docs.aws.amazon.com/IAM/latest/UserGuide/introduction.html",
              provider: "Amazon Web Services",
              resourceType: "official_docs",
              level: "beginner",
              isFree: true,
              isOfficial: true,
              qualityScore: 99,
              interactive: false,
              projectBased: false,
              estimatedMinutes: 50,
              status: "active",
              isPrimary: true,
              whyThisResource: "The definitive guide to IAM policies, roles, permissions boundaries, and security credentials.",
            },
            alternativeResource: {
              id: "res-aws-skills-builder",
              title: "AWS Skill Builder: Cloud Practitioner Essentials (Free Course)",
              url: "https://explore.skillbuilder.aws/learn/course/external/view/elearning/134/aws-cloud-practitioner-essentials",
              provider: "AWS Training & Certification",
              resourceType: "structured_course",
              level: "beginner",
              isFree: true,
              isOfficial: true,
              qualityScore: 94,
              interactive: true,
              projectBased: false,
              estimatedMinutes: 90,
              status: "active",
              isPrimary: false,
              whyThisResource: "Official free interactive course directly from Amazon training engineers.",
            },
            practiceTasks: [
              {
                id: "aws-prac-iam-1",
                title: "Write an IAM Policy Enforcing Least-Privilege S3 Access",
                description: "Write a JSON IAM policy allowing read-only access (`s3:GetObject`, `s3:ListBucket`) strictly to a designated bucket prefix.",
                difficulty: "beginner",
                expectedOutcome: "Policy successfully validates in IAM policy simulator without wildcard overprivileging.",
                verificationMethod: "manual_check",
                order: 1,
              },
            ],
            checkpoint: {
              id: "aws-chk-iam",
              title: "IAM & Access Control Checkpoint",
              description: "Validate understanding of IAM roles vs access keys.",
              checkpointType: "quiz",
              questions: [
                {
                  id: "aws-iam-q1",
                  question: "How should an application running on an EC2 instance securely access AWS resources (like S3 or DynamoDB)?",
                  options: [
                    "Attach an IAM Role directly to the EC2 instance profile",
                    "Hardcode root account access keys into the application code",
                    "Save IAM user access keys in an unencrypted file in the git repository",
                    "Configure the S3 bucket to be completely public to the internet",
                  ],
                  correctIndex: 0,
                  explanation: "Attaching an IAM Role allows AWS to deliver temporary rotating credentials automatically via instance metadata.",
                },
              ],
              verificationCriteria: ["Explain IAM roles and temporary credentials."],
            },
          },
        ],
      },
      {
        id: "aws-mod-2",
        title: "Networking (VPC) & Compute (EC2)",
        description: "Virtual Private Clouds (VPC), public vs private subnets, internet gateways, NAT gateways, route tables, and EC2 instances.",
        level: "intermediate",
        order: 2,
        estimatedHours: 8,
        topics: [
          {
            id: "aws-top-vpc",
            title: "Virtual Private Cloud (VPC), Subnets & Security Groups",
            description: "Architect a dual-availability-zone VPC with public subnets for load balancers and private subnets for application servers.",
            order: 1,
            required: true,
            estimatedMinutes: 90,
            prerequisites: ["aws-top-iam"],
            primaryResource: {
              id: "res-aws-vpc-official",
              title: "AWS Official Documentation: Amazon VPC User Guide",
              url: "https://docs.aws.amazon.com/vpc/latest/userguide/what-is-amazon-vpc.html",
              provider: "Amazon Web Services",
              resourceType: "official_docs",
              level: "intermediate",
              isFree: true,
              isOfficial: true,
              qualityScore: 98,
              interactive: false,
              projectBased: false,
              estimatedMinutes: 60,
              status: "active",
              isPrimary: true,
              whyThisResource: "Detailed architectural instructions for subnets, route tables, security groups, and network ACLs.",
            },
            practiceTasks: [
              {
                id: "aws-prac-vpc-1",
                title: "Design a High-Availability Multi-AZ VPC Architecture",
                description: "Map CIDR blocks for 2 Public Subnets and 2 Private Subnets across 2 Availability Zones with Route Tables and an Internet Gateway.",
                difficulty: "intermediate",
                expectedOutcome: "CIDR blocks do not overlap and public subnets route 0.0.0.0/0 to the Internet Gateway.",
                verificationMethod: "manual_check",
                order: 1,
              },
            ],
          },
          {
            id: "aws-top-ec2-alb",
            title: "EC2 Auto-Scaling & Application Load Balancers (ALB)",
            description: "Deploy stateless web servers behind an ALB with Target Groups, health checks, and Launch Templates.",
            order: 2,
            required: true,
            estimatedMinutes: 80,
            prerequisites: ["aws-top-vpc"],
            primaryResource: {
              id: "res-aws-ec2-official",
              title: "AWS Official Documentation: Amazon EC2 User Guide for Linux Instances",
              url: "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/concepts.html",
              provider: "Amazon Web Services",
              resourceType: "official_docs",
              level: "intermediate",
              isFree: true,
              isOfficial: true,
              qualityScore: 97,
              interactive: false,
              projectBased: false,
              estimatedMinutes: 50,
              status: "active",
              isPrimary: true,
              whyThisResource: "Covers EC2 instance lifecycles, user data bootstrap scripts, security groups, and key pairs.",
            },
          },
        ],
      },
      {
        id: "aws-mod-3",
        title: "Storage (S3) & Managed Relational Databases (RDS)",
        description: "S3 object storage, versioning, lifecycle policies, RDS PostgreSQL deployment, multi-AZ failover, and automated backups.",
        level: "intermediate",
        order: 3,
        estimatedHours: 6,
        topics: [
          {
            id: "aws-top-s3",
            title: "Amazon S3: Buckets, Security & Lifecycle Rules",
            description: "Store assets in S3, configure pre-signed URLs for secure client uploads, and transition old files to Glacier.",
            order: 1,
            required: true,
            estimatedMinutes: 70,
            prerequisites: ["aws-top-iam"],
            primaryResource: {
              id: "res-aws-s3-official",
              title: "AWS Official Documentation: Amazon S3 User Guide",
              url: "https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html",
              provider: "Amazon Web Services",
              resourceType: "official_docs",
              level: "intermediate",
              isFree: true,
              isOfficial: true,
              qualityScore: 98,
              interactive: false,
              projectBased: false,
              estimatedMinutes: 50,
              status: "active",
              isPrimary: true,
              whyThisResource: "Full coverage of S3 storage classes, bucket policies, encryption, and pre-signed URLs.",
            },
          },
          {
            id: "aws-top-rds",
            title: "Amazon RDS: Multi-AZ Databases & Read Replicas",
            description: "Provision a managed PostgreSQL database in private subnets, configure automated snapshots, and set up read replicas.",
            order: 2,
            required: true,
            estimatedMinutes: 75,
            prerequisites: ["aws-top-vpc"],
            primaryResource: {
              id: "res-aws-rds-official",
              title: "AWS Official Documentation: Amazon RDS User Guide",
              url: "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Welcome.html",
              provider: "Amazon Web Services",
              resourceType: "official_docs",
              level: "intermediate",
              isFree: true,
              isOfficial: true,
              qualityScore: 97,
              interactive: false,
              projectBased: false,
              estimatedMinutes: 50,
              status: "active",
              isPrimary: true,
              whyThisResource: "Covers RDS multi-AZ failovers, parameter groups, VPC database subnet groups, and maintenance windows.",
            },
          },
        ],
      },
      {
        id: "aws-mod-4",
        title: "Observability (CloudWatch) & Cost Optimization",
        description: "Monitor CPU, disk, memory, set up CloudWatch alarms with SNS notifications, and manage AWS Free Tier cost budgets.",
        level: "advanced",
        order: 4,
        estimatedHours: 6,
        topics: [
          {
            id: "aws-top-cloudwatch",
            title: "Amazon CloudWatch & Alerting with SNS",
            description: "Ingest logs, configure CloudWatch metric filters, and trigger alarms on 5xx error rate spikes or high latency.",
            order: 1,
            required: true,
            estimatedMinutes: 75,
            prerequisites: ["aws-top-ec2-alb"],
            primaryResource: {
              id: "res-aws-cloudwatch-official",
              title: "AWS Official Documentation: Amazon CloudWatch User Guide",
              url: "https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/WhatIsCloudWatch.html",
              provider: "Amazon Web Services",
              resourceType: "official_docs",
              level: "advanced",
              isFree: true,
              isOfficial: true,
              qualityScore: 97,
              interactive: false,
              projectBased: false,
              estimatedMinutes: 50,
              status: "active",
              isPrimary: true,
              whyThisResource: "Essential manual for real-time observability, dashboards, and automated operational actions.",
            },
          },
        ],
      },
    ],
    implementationTasks: [
      {
        id: "aws-impl-infra",
        title: "Deploy a Scalable Web Backend on AWS",
        description: "Deploy a backend API onto EC2 instances behind an Application Load Balancer connected to an RDS PostgreSQL database.",
        requirements: [
          "Create a customized VPC with 2 public and 2 private subnets across 2 Availability Zones.",
          "Launch an RDS PostgreSQL instance strictly accessible within private subnets via Security Group rules.",
          "Deploy the web application on EC2 using an IAM instance profile (zero static AWS keys in code).",
          "Integrate direct image file uploads using AWS SDK pre-signed S3 URLs.",
          "Set up CloudWatch CPU alarms (>80% for 5 mins) sending alerts to an SNS email topic.",
        ],
        expectedTechnologies: ["AWS VPC", "AWS EC2", "AWS RDS", "AWS S3", "AWS CloudWatch", "Terraform or AWS CLI"],
        difficulty: "intermediate",
        estimatedHours: 10,
        order: 1,
        isCapstone: false,
      },
    ],
    capstoneProject: {
      id: "aws-capstone-main",
      title: "Production Cloud Infrastructure & Automated Deployment Architecture",
      description: "Design and implement a secure, highly-available, cost-optimized cloud architecture on AWS for a modern web application.",
      architectureOverview: "A resilient multi-AZ topology featuring public Application Load Balancers, containerized application servers running on ECS/EC2 in private subnets, Amazon Aurora/RDS PostgreSQL with automated backups, S3 asset storage with CloudFront CDN distribution, and CloudWatch operational alarms.",
      requirements: [
        "VPC network architecture isolated across 2 Availability Zones with NAT Gateways.",
        "Zero credentials in code: all access governed by IAM Roles and AWS Secrets Manager.",
        "Application Load Balancer terminating TLS/SSL certificates from AWS Certificate Manager (ACM).",
        "Encrypted S3 bucket with CloudFront CDN and Origin Access Control (OAC).",
        "Amazon RDS PostgreSQL with automated snapshot retention and read-replica capability.",
        "CloudWatch billing alarm preventing unexpected AWS Free Tier overages.",
      ],
      expectedTechnologies: ["AWS (VPC, EC2, RDS, S3, CloudFront, CloudWatch)", "Terraform or CloudFormation", "Docker"],
      estimatedHours: 15,
      portfolioDeliverables: {
        githubRepoRequired: true,
        readmeSpec: "Comprehensive architecture diagram, Terraform or CloudFormation scripts, and security validation documentation.",
        liveDemoSuggested: true,
      },
    },
  },

  // ==========================================
  // 4. REDIS
  // ==========================================
  Redis: {
    skillId: "Redis",
    canonicalSkill: "Redis",
    version: 1,
    description: "Ultra-fast in-memory data store used as a database, cache, streaming engine, and message broker.",
    targetRoles: ["Backend Engineer", "System Architect", "Distributed Systems Engineer"],
    prerequisites: ["Data Structures (Hash Maps, Sets, Lists)", "Basic Backend API Development"],
    estimatedHours: 18,
    whyItMatters: "Redis delivers sub-millisecond data access. Modern distributed architectures rely on Redis for session storage, API rate limiting, caching layers, pub/sub queues, and distributed locks.",
    modules: [
      {
        id: "redis-mod-1",
        title: "In-Memory Architecture & Core Data Types",
        description: "Single-threaded event loop, in-memory performance, Strings, Hashes, Lists, Sets, and Sorted Sets.",
        level: "beginner",
        order: 1,
        estimatedHours: 4,
        topics: [
          {
            id: "redis-top-datatypes",
            title: "Redis Data Structures & Time Complexity",
            description: "Master GET/SET, MGET, Hashes (HSET/HGETALL), Lists (LPUSH/RPOP), and Sorted Sets (ZADD/ZRANGEBYSCORE).",
            order: 1,
            required: true,
            estimatedMinutes: 60,
            prerequisites: [],
            primaryResource: {
              id: "res-redis-datatypes-official",
              title: "Redis Official Documentation: Understanding Redis Data Types",
              url: "https://redis.io/docs/latest/develop/data-types/",
              provider: "Redis Ltd.",
              resourceType: "official_docs",
              level: "beginner",
              isFree: true,
              isOfficial: true,
              qualityScore: 99,
              interactive: false,
              projectBased: false,
              estimatedMinutes: 45,
              status: "active",
              isPrimary: true,
              whyThisResource: "The canonical reference detailing commands, memory footprint, and big-O time complexity.",
            },
            alternativeResource: {
              id: "res-redis-try",
              title: "Redis University: RU101 Introduction to Redis Data Structures",
              url: "https://university.redis.com/courses/ru101/",
              provider: "Redis University",
              resourceType: "structured_course",
              level: "beginner",
              isFree: true,
              isOfficial: true,
              qualityScore: 95,
              interactive: true,
              projectBased: true,
              estimatedMinutes: 60,
              status: "active",
              isPrimary: false,
              whyThisResource: "Official free video course and certification track from the creators of Redis.",
            },
            practiceTasks: [
              {
                id: "redis-prac-zset-1",
                title: "Build a Real-Time Gaming Leaderboard with Sorted Sets",
                description: "Use `ZADD` to insert player scores, `ZINCRBY` for live updates, and `ZREVRANGE` to query the top 10 players.",
                difficulty: "beginner",
                expectedOutcome: "Sorted set returns real-time rank queries in O(log(N)+M) time.",
                verificationMethod: "code_execution",
                order: 1,
              },
            ],
          },
        ],
      },
      {
        id: "redis-mod-2",
        title: "Caching Strategies, TTL & Eviction Policies",
        description: "Cache-Aside, Write-Through, Write-Behind patterns, TTL expiration, and memory eviction policies (LRU, LFU).",
        level: "intermediate",
        order: 2,
        estimatedHours: 5,
        topics: [
          {
            id: "redis-top-caching-patterns",
            title: "Cache-Aside Pattern, Expiration & Eviction Policies",
            description: "Implement Cache-Aside with EXPIRE TTL, handle cache stampedes with mutexes, and configure maxmemory-policy.",
            order: 1,
            required: true,
            estimatedMinutes: 80,
            prerequisites: ["redis-top-datatypes"],
            primaryResource: {
              id: "res-redis-caching-guide",
              title: "Redis Official Documentation: Key Expiration & Memory Optimization",
              url: "https://redis.io/docs/latest/develop/use/keyspace/",
              provider: "Redis Ltd.",
              resourceType: "official_docs",
              level: "intermediate",
              isFree: true,
              isOfficial: true,
              qualityScore: 97,
              interactive: false,
              projectBased: false,
              estimatedMinutes: 50,
              status: "active",
              isPrimary: true,
              whyThisResource: "In-depth explanation of active/passive key expiration, volatile-lru, and allkeys-lru eviction.",
            },
            practiceTasks: [
              {
                id: "redis-prac-cache-1",
                title: "Implement API Cache-Aside Middleware with Graceful Fallback",
                description: "Write backend middleware that intercepts GET requests, checks Redis cache, returns on cache hit, or fetches DB and caches with 60s TTL on miss.",
                difficulty: "intermediate",
                expectedOutcome: "Subsequent requests return cached JSON in under 3ms without querying database.",
                verificationMethod: "code_execution",
                order: 1,
              },
            ],
          },
        ],
      },
      {
        id: "redis-mod-3",
        title: "Persistence, Transactions & Distributed Locking",
        description: "RDB snapshots vs AOF logs, Redis transactions with MULTI/EXEC, and distributed locking with Redlock algorithm.",
        level: "advanced",
        order: 3,
        estimatedHours: 5,
        topics: [
          {
            id: "redis-top-distributed-locks",
            title: "Distributed Locks with Redis & Atomic Scripting",
            description: "Acquire safe distributed locks using SET resource_name my_random_value NX PX 30000 and release atomically via Lua scripts.",
            order: 1,
            required: true,
            estimatedMinutes: 85,
            prerequisites: ["redis-top-caching-patterns"],
            primaryResource: {
              id: "res-redis-distlock-official",
              title: "Redis Official Documentation: Distributed Locks with Redis (Redlock)",
              url: "https://redis.io/docs/latest/develop/use/patterns/distributed-locks/",
              provider: "Redis Ltd.",
              resourceType: "official_docs",
              level: "advanced",
              isFree: true,
              isOfficial: true,
              qualityScore: 98,
              interactive: false,
              projectBased: false,
              estimatedMinutes: 50,
              status: "active",
              isPrimary: true,
              whyThisResource: "The classic algorithmic breakdown of distributed locking, lease timeouts, and race-condition free releases.",
            },
            practiceTasks: [
              {
                id: "redis-prac-lock-1",
                title: "Implement an Atomic Distributed Lock with Lua Script Release",
                description: "Write a lock manager that sets a unique UUID with NX and PX, and executes a Lua script to only delete the key if the UUID matches.",
                difficulty: "advanced",
                expectedOutcome: "Competing concurrent workers cannot execute the critical section simultaneously.",
                verificationMethod: "code_execution",
                order: 1,
              },
            ],
          },
        ],
      },
    ],
    implementationTasks: [
      {
        id: "redis-impl-rate-limiter",
        title: "Build a High-Throughput Token Bucket Rate Limiter with Redis",
        description: "Create an API rate-limiting middleware that restricts client requests per IP or API key using Redis atomic counters or sliding window logs.",
        requirements: [
          "Implement Sliding Window Log or Token Bucket algorithm in Redis.",
          "Use Redis pipelines or Lua scripts for atomic evaluation.",
          "Return standard HTTP headers: X-RateLimit-Limit, X-RateLimit-Remaining, and X-RateLimit-Reset.",
          "Handle Redis outages gracefully with fail-open or local in-memory fallback.",
        ],
        expectedTechnologies: ["Redis", "Node.js / Python / Go", "Docker"],
        difficulty: "intermediate",
        estimatedHours: 8,
        order: 1,
        isCapstone: false,
      },
    ],
    capstoneProject: {
      id: "redis-capstone-main",
      title: "Real-Time Multi-Tenant Caching Layer & Distributed Task Queue",
      description: "Build a high-scale caching and pub/sub message processing infrastructure that accelerates database reads and orchestrates asynchronous background worker jobs.",
      architectureOverview: "A hybrid Redis architecture combining Cache-Aside caching with TTL jitter, Redis Streams for reliable message delivery with consumer groups, and distributed mutex locking for critical checkout and transaction operations.",
      requirements: [
        "Cache-Aside implementation for relational database queries with TTL jitter to prevent cache stampedes.",
        "Sliding-window API rate limiter handling 1,000 requests per minute per IP.",
        "Distributed lock mechanism with automatic renewal (heartbeat) and atomic Lua release.",
        "Pub/Sub or Redis Streams worker queue with consumer group acknowledge (XACK) mechanics.",
        "Performance benchmarks demonstrating 95% reduction in primary database query load.",
      ],
      expectedTechnologies: ["Redis 7+", "Node.js / Python / Go", "PostgreSQL", "Docker"],
      estimatedHours: 12,
      portfolioDeliverables: {
        githubRepoRequired: true,
        readmeSpec: "Include architecture diagram, benchmark graphs (RPS & latency before and after Redis), and Docker Compose environment.",
        liveDemoSuggested: true,
      },
    },
  },

  // ==========================================
  // 5. REACT
  // ==========================================
  React: {
    skillId: "React",
    canonicalSkill: "React",
    version: 1,
    description: "The declarative, component-based UI library for building responsive, high-performance web applications.",
    targetRoles: ["Frontend Developer", "Full Stack Engineer", "Web Application Developer"],
    prerequisites: ["Modern JavaScript (ES6+, Promises, Destructuring)", "HTML5 & CSS3"],
    estimatedHours: 22,
    whyItMatters: "React powers modern web user interfaces worldwide. Mastery of the React component model, hooks, custom hooks, state management, and performance optimization is a baseline requirement for frontend and full-stack positions.",
    modules: [
      {
        id: "react-mod-1",
        title: "JSX, Components, Props & State Primitives",
        description: "Declarative UI rendering, component hierarchy, props vs state, and immutable state updates with useState.",
        level: "beginner",
        order: 1,
        estimatedHours: 4,
        topics: [
          {
            id: "react-top-hooks-state",
            title: "Component State with useState & useReducer",
            description: "Manage component state, updater functions for state depending on previous values, and complex state machines with useReducer.",
            order: 1,
            required: true,
            estimatedMinutes: 65,
            prerequisites: [],
            primaryResource: {
              id: "res-react-state-official",
              title: "React Official Documentation (react.dev): State as a Snapshot",
              url: "https://react.dev/learn/state-a-components-memory",
              provider: "Meta Open Source",
              resourceType: "official_docs",
              level: "beginner",
              isFree: true,
              isOfficial: true,
              qualityScore: 99,
              interactive: true,
              projectBased: false,
              estimatedMinutes: 45,
              status: "active",
              isPrimary: true,
              whyThisResource: "The canonical modern React documentation with interactive code sandboxes in every lesson.",
            },
            practiceTasks: [
              {
                id: "react-prac-state-1",
                title: "Build a Complex Multi-Step Form with useReducer",
                description: "Implement a 3-step registration wizard with form validation, step navigation, and centralized state transitions via useReducer.",
                difficulty: "beginner",
                expectedOutcome: "Form state transitions cleanly without prop drilling or out-of-sync local variables.",
                verificationMethod: "manual_check",
                order: 1,
              },
            ],
          },
          {
            id: "react-top-effects",
            title: "Lifecycle Synchronization with useEffect",
            description: "Fetch API data, subscribe to browser events, manage dependency arrays, and write cleanup functions to prevent memory leaks.",
            order: 2,
            required: true,
            estimatedMinutes: 75,
            prerequisites: ["react-top-hooks-state"],
            primaryResource: {
              id: "res-react-effects-official",
              title: "React Official Documentation (react.dev): Synchronizing with Effects",
              url: "https://react.dev/learn/synchronizing-with-effects",
              provider: "Meta Open Source",
              resourceType: "official_docs",
              level: "beginner",
              isFree: true,
              isOfficial: true,
              qualityScore: 99,
              interactive: true,
              projectBased: false,
              estimatedMinutes: 50,
              status: "active",
              isPrimary: true,
              whyThisResource: "Essential guide to avoiding common useEffect pitfalls and race conditions during async fetches.",
            },
          },
        ],
      },
      {
        id: "react-mod-2",
        title: "Custom Hooks & Global State Management",
        description: "Encapsulate stateful logic into reusable custom hooks, Context API, and lightweight external stores like Zustand.",
        level: "intermediate",
        order: 2,
        estimatedHours: 6,
        topics: [
          {
            id: "react-top-custom-hooks",
            title: "Authoring Reusable Custom Hooks",
            description: "Extract common logic into reusable hooks (useDebounce, useLocalStorage, useWindowSize, useFetchWithRetry).",
            order: 1,
            required: true,
            estimatedMinutes: 80,
            prerequisites: ["react-top-effects"],
            primaryResource: {
              id: "res-react-custom-hooks-official",
              title: "React Official Documentation (react.dev): Reusing Logic with Custom Hooks",
              url: "https://react.dev/learn/reusing-logic-with-custom-hooks",
              provider: "Meta Open Source",
              resourceType: "official_docs",
              level: "intermediate",
              isFree: true,
              isOfficial: true,
              qualityScore: 98,
              interactive: true,
              projectBased: false,
              estimatedMinutes: 50,
              status: "active",
              isPrimary: true,
              whyThisResource: "Best practices for extracting stateful business logic into composable, testable custom hooks.",
            },
            practiceTasks: [
              {
                id: "react-prac-hook-1",
                title: "Build a useDebounce Hook for Search Autocompletion",
                description: "Create a custom hook that delays updating a search term until the user has ceased typing for 300ms.",
                difficulty: "intermediate",
                expectedOutcome: "Typing in input triggers fetch only once after typing pauses, eliminating excessive network requests.",
                verificationMethod: "code_execution",
                order: 1,
              },
            ],
          },
        ],
      },
      {
        id: "react-mod-3",
        title: "Performance Optimization, Profiling & Modern Concurrent UI",
        description: "Prevent unnecessary re-renders with memo, useMemo, useCallback, useTransition, Suspense, and React Developer Tools Profiler.",
        level: "advanced",
        order: 3,
        estimatedHours: 6,
        topics: [
          {
            id: "react-top-performance",
            title: "Performance Tuning: memo, useMemo, useCallback & Profiling",
            description: "Profile components, fix expensive wasted renders, ensure stable object references, and virtualize large lists.",
            order: 1,
            required: true,
            estimatedMinutes: 85,
            prerequisites: ["react-top-custom-hooks"],
            primaryResource: {
              id: "res-react-performance-official",
              title: "React Official Documentation: useMemo & Optimizing Re-renders",
              url: "https://react.dev/reference/react/useMemo",
              provider: "Meta Open Source",
              resourceType: "official_docs",
              level: "advanced",
              isFree: true,
              isOfficial: true,
              qualityScore: 98,
              interactive: true,
              projectBased: false,
              estimatedMinutes: 50,
              status: "active",
              isPrimary: true,
              whyThisResource: "Clear rules on when memoization is actually beneficial versus when it adds unnecessary overhead.",
            },
          },
        ],
      },
    ],
    implementationTasks: [
      {
        id: "react-impl-dashboard",
        title: "Build a Real-Time Interactive Analytics Dashboard",
        description: "Develop a responsive dashboard featuring data filtering, debounced search, custom hooks, and optimistic state updates.",
        requirements: [
          "Implement dark/light theme switching with local storage persistence.",
          "Build custom hooks for window dimensions and debounced search.",
          "Integrate client-side sorting, filtering, and pagination on a dataset of 500+ records.",
          "Optimize rendering with React.memo and useCallback to ensure 60fps interaction during data filtering.",
        ],
        expectedTechnologies: ["React 18+", "TypeScript", "Tailwind CSS or Vanilla CSS", "Lucide Icons"],
        difficulty: "intermediate",
        estimatedHours: 8,
        order: 1,
        isCapstone: false,
      },
    ],
    capstoneProject: {
      id: "react-capstone-main",
      title: "Interactive Project Management Workspace with Drag & Drop",
      description: "Build an enterprise-grade Kanban board and productivity workspace with drag-and-drop task sorting, real-time collaboration updates, and optimistic UI mutations.",
      architectureOverview: "A single-page application utilizing Zustand for global state, custom hooks for persistent browser storage, virtualization for smooth rendering of hundreds of task cards, and comprehensive unit/integration test coverage.",
      requirements: [
        "Drag-and-drop reordering of tasks across columns with optimistic UI updates.",
        "Custom modal dialogs for task creation, editing, and tag management.",
        "Debounced full-text search with highlighting and multi-tag filtering.",
        "Zero unnecessary re-renders across sibling columns when a single card updates.",
        "Responsive mobile-friendly design with complete keyboard accessibility (a11y).",
      ],
      expectedTechnologies: ["React 18/19", "TypeScript", "Zustand / Context", "CSS Modules or Tailwind", "Vite / Next.js"],
      estimatedHours: 12,
      portfolioDeliverables: {
        githubRepoRequired: true,
        readmeSpec: "Detailed README with animated GIF preview, state architecture overview, and component breakdown.",
        liveDemoSuggested: true,
      },
    },
  },
};

/**
 * High-value default domain blueprints for:
 * MySQL, MongoDB, Kubernetes, Git, TypeScript, JavaScript, Node.js, Python, Java, Spring Boot, REST APIs, GraphQL, SQL, HTML, CSS.
 * These guarantee distinct curricula for 20+ technologies without falling back to generic placeholders.
 */
export const ADDITIONAL_SKILL_TEMPLATES: Record<string, Partial<SkillCurriculumDefinition>> = {
  TypeScript: {
    description: "Typed superset of JavaScript providing static type checking, interfaces, generics, and enterprise-scale maintainability.",
    whyItMatters: "TypeScript is the standard across modern frontend and backend codebases. It prevents entire categories of runtime exceptions before deployment.",
    prerequisites: ["Modern JavaScript (ES6+)"],
    estimatedHours: 18,
    targetRoles: ["Full Stack Developer", "Frontend Engineer", "Node.js Backend Developer"],
  },
  Kubernetes: {
    description: "Production-grade container orchestration system automating deployment, scaling, and management of containerized applications.",
    whyItMatters: "Kubernetes is the standard runtime platform across enterprise cloud environments. Teams rely on it for automated failover, zero-downtime rollouts, and multi-service scaling.",
    prerequisites: ["Docker & Containers", "Basic Linux Networking"],
    estimatedHours: 24,
    targetRoles: ["DevOps Engineer", "Cloud Engineer", "Site Reliability Engineer (SRE)"],
  },
  MongoDB: {
    description: "Document-oriented NoSQL database designed for high availability, flexible JSON-like schemas, and horizontal scaling.",
    whyItMatters: "MongoDB powers high-speed content management, event-logging, and prototyping workflows where relational schema rigidity is a bottleneck.",
    prerequisites: ["JSON Data Structures", "Basic Backend Development"],
    estimatedHours: 16,
    targetRoles: ["Full Stack Developer", "Backend Engineer"],
  },
  Git: {
    description: "Distributed version control system essential for tracking code changes, branching strategies, and team collaboration.",
    whyItMatters: "Version control is the bedrock of modern software engineering. Mastery of interactive rebasing, merge conflict resolution, and Git workflows is mandatory.",
    prerequisites: ["Command Line Basics"],
    estimatedHours: 10,
    targetRoles: ["Software Engineer", "Frontend Developer", "Backend Developer"],
  },
  Python: {
    description: "Versatile, high-level programming language renowned for clear syntax, backend APIs, data engineering, and machine learning.",
    whyItMatters: "Python dominates AI, automation, backend web services (FastAPI, Django), and data processing pipelines worldwide.",
    prerequisites: ["Basic Programming Logic"],
    estimatedHours: 20,
    targetRoles: ["Python Developer", "Backend Engineer", "Data Engineer", "AI/ML Engineer"],
  },
  "Node.js": {
    description: "Asynchronous, event-driven JavaScript runtime for building high-concurrency, scalable network applications and REST APIs.",
    whyItMatters: "Node.js unifies frontend and backend languages, powering microservices and real-time streaming architectures across thousands of startups and enterprises.",
    prerequisites: ["JavaScript Fundamentals", "Asynchronous Programming (Promises, async/await)"],
    estimatedHours: 20,
    targetRoles: ["Backend Engineer", "Full Stack Developer"],
  },
};

/**
 * Retrieves a curated curriculum definition for a skill.
 * If the skill is in SEEDED_CURRICULA, returns it.
 * Otherwise, synthesizes a domain-tailored distinct curriculum based on skill characteristics.
 */
export function getCurriculumDefinition(canonicalSkill: string): SkillCurriculumDefinition | null {
  if (SEEDED_CURRICULA[canonicalSkill]) {
    return SEEDED_CURRICULA[canonicalSkill];
  }

  // Case-insensitive match check
  for (const [key, value] of Object.entries(SEEDED_CURRICULA)) {
    if (key.toLowerCase() === canonicalSkill.toLowerCase()) {
      return value;
    }
  }

  return null;
}
